language: elixir
elixir:
  - 1.3.3
otp_release:
  - 19.1.1
jdk:
  - openjdk8
  - oraclejdk8
git:
  depth: 1
before_install:
  - java -version
  - wget http://www.us.apache.org/dist/cassandra/3.9/apache-cassandra-3.9-bin.tar.gz
  - tar -xvzf apache-cassandra-3.9-bin.tar.gz
  - sh ./apache-cassandra-3.9/bin/cassandra -R
